FPS = 60

BOMB_WIDTH = 60
BOMB_HEIGHT = 60

FIRST_BOMB_STATE = 40
SECOND_BOMB_STATE = 80
THIRD_BOMB_STATE = 120
FOURTH_BOMB_STATE = 160

BOMB_IMAGE_1 = 'assets/bomb/bomb1.png'
BOMB_IMAGE_2 = 'assets/bomb/bomb2.png'
BOMB_IMAGE_3 = 'assets/bomb/bomb3.png'
FIRE_IMAGE = 'assets/bomb/fire.png'
TILE_SIZE = 60

CIRCLE_RADIUS = 100
MENU_TEXT_FONT_SIZE = 75

PLAYER_FONT_SIZE = 18
PLAYER_TEXT_Y_POS = 235

PLAYER_ONE_X_POS = 240
PLAYER_TWO_X_POS = 640
PLAYER_THREE_X_POS = 1040

CIRCLE_Y_POS = 360
CENTER_X_POS = 640
